### ISSUE TITLE
unable to login Linshare Admin interface.

### ISSUE THREAD

**Issue by georgej77** [linagora/linshare-thumbnail-server#2]
Hi,
I can able to login User interface of linshare. But i cannot login to Admin interface. I have used below login credentials to access it. 

Login: root@localhost.localdomain

Password: adminlinshare

I have deployed it on Centos7.
Any one help me on it.

**Comment by fmartin-linagora** [comment]
Hi,
Sorry but I think you created this issue in the wrong repository. For any issue, question or hep, please create an issue here https://github.com/linagora/linshare.
When you will do it, please detail it as much as you can : 
* Which version of LinShare have you installed ?
* What is the problem ? screenshots ? logs ? (/var/log/tomcat/)
Fred.

**Comment by georgej77** [comment]
Hi Fred,

I have resolved the issue . Now i can access linshare admin console.
Once i disabled the ipv6, i can access the console.
 cat /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.enp0s3.disable_ipv6 = 1

George

**Comment by tamalindia** [comment]
Hi All,

I have installed Linshare to my Centos7 system and user interface is working fine. But in the admin interface it showing blank.
![image](https://user-images.githubusercontent.com/62827668/96563357-7a12ee00-12df-11eb-8aea-6449982a0308.png)
Could any one suggest any help?

Regards

**Comment by georgej77** [comment]
Hi,

Can you share apache config, and tomcat config ( /etc/sysconfig/tomcat)
Please disable IPv6 too
cat /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.enp0s3.disable_ipv6 = 1

**Comment by tamalindia** [comment]
Dear Annmaria,

I am sharing with you the required apache config and tomcat config file
attached with this mail. Please note I have already disabled the IPv6 for
my server. Please check the both config file and help me to resolve the
issue at the earliest.

Thanks & regards

Tamal

**Comment by fmartin-linagora** [comment]
Hi,

If the admin interface is not showing the login dialog, it means the admin application was not able to reach the backend, either the backend is not running properly (See tomcat's logs) or there is a proxy pass issue in the Apache HTTP configuration (see its logs).

**Comment by sidri69** [comment]
Hello everyone,
I recently encountered this error. It comes from the line #JAVA_OPTS="-Djava.awt.headless=true" that needs to be commented in the /etc/default/tomcat9 file.
Don't forget to set MongoDB to enable.
I hope this helps some of you.
