### ISSUE TITLE
How to configure uploadrequest and uploadproposition

### ISSUE THREAD

**Issue by georgej77** [linagora/linshare-thumbnail-server#3]
Please share me the configuration guide for linshare uploadrequest and uploadproposition.
How can i use it. Hope i get the support from you.

**Comment by fmartin-linagora** [comment]
Hi,
We only have this documentation about upload request and upload proposition (https://github.com/linagora/linshare/blob/maintenance-1.12.x/documentation/EN/installation/linshare-install.md#instalUR)
NB: These two functionalities are only available for LinShare 1.x. There are not back-port yet on 2.x.

**Comment by fmartin-linagora** [comment]
BTW, It is better if you ask you questions [here](https://github.com/linagora/linshare/). This repository is only for LinShare Thumbail server component.

**Comment by georgej77** [comment]
Thank you.
Let me try to do it on Linshare 1.x
